### PR TITLE
Don't depend on void + semigroups on newer GHC

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Make sure you also adjust the CPP bounds [here](https://github.com/ekmett/contravariant/blob/4982c021a52391c75dabd64dac8df529af16a371/src/Data/Functor/Contravariant.hs#L98) and [here](https://github.com/ekmett/contravariant/blob/4982c021a52391c75dabd64dac8df529af16a371/src/Data/Functor/Contravariant.hs#L378) so that it'll compile on GHC 8.0+ even with `-f-semigroups`.

**Comment by phadej** [comment]
@RyanGlScott done

**Comment by RyanGlScott** [comment]
Thanks! I see you linked to this from another issue - do you need a new version of `contravariant` to be released soon to fix that?

**Comment by phadej** [comment]
@RyanGlScott Eventually. As I see there are no other changes in `master` atm since `1.4`, is there something holding`1.4.0.1` from being released (except Edward's queue being too long)?

**Pull request merged**
